import { defineConfig } from "tinacms";

const branch =
  process.env.GITHUB_BRANCH ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "gallery",
        label: "Galerie",
        path: "content/gallery",
        fields: [
          { type: "number", name: "year", label: "Rok ročníku", required: true },
          { type: "string", name: "description", label: "Popis ročníku" },
          { type: "string", name: "youtubeUrl", label: "YouTube video URL (volitelné)" },
          { type: "image", name: "photos", label: "Fotky", list: true },
        ],
      },
      // ── Page singleton collections ──────────────────────────────────────
      {
        name: "home",
        label: "Úvodní stránka",
        path: "content/pages",
        match: { include: "home" },
        fields: [
          { type: "string", name: "heroHeadline", label: "Hero — Nadpis" },
          { type: "string", name: "heroSubtext", label: "Hero — Podnadpis", ui: { component: "textarea" } },
          { type: "string", name: "heroCta1Label", label: "Hero — CTA 1 text" },
          { type: "string", name: "heroCta1Href", label: "Hero — CTA 1 odkaz" },
          { type: "string", name: "heroCta2Label", label: "Hero — CTA 2 text" },
          { type: "string", name: "heroCta2Href", label: "Hero — CTA 2 odkaz" },
          { type: "string", name: "storyHeading", label: "Příběh — Nadpis" },
          { type: "string", name: "storyBody", label: "Příběh — Text", ui: { component: "textarea" } },
          { type: "string", name: "storyQuote", label: "Příběh — Citát", ui: { component: "textarea" } },
          { type: "string", name: "storyQuoteAuthor", label: "Příběh — Autor citátu" },
          { type: "string", name: "storyLinkLabel", label: "Příběh — Odkaz text" },
          { type: "string", name: "campHeading", label: "O kempu — Nadpis sekce" },
          { type: "string", name: "campBody", label: "O kempu — Popis", ui: { component: "textarea" } },
          { type: "string", name: "campActivitiesHeading", label: "O kempu — Nadpis aktivit" },
          {
            type: "object",
            name: "campActivities",
            label: "O kempu — Aktivity",
            list: true,
            fields: [
              { type: "string", name: "title", label: "Název aktivity" },
              { type: "string", name: "description", label: "Popis", ui: { component: "textarea" } },
            ],
          },
          { type: "string", name: "quoteText", label: "Citát — Text", ui: { component: "textarea" } },
          { type: "string", name: "quoteAuthor", label: "Citát — Autor" },
          { type: "string", name: "photoStripHeading", label: "Fotopás — Nadpis" },
          { type: "string", name: "rozcestnikHeading", label: "Rozcestník — Nadpis" },
          { type: "string", name: "rozcestnikSubheading", label: "Rozcestník — Podnadpis" },
          {
            type: "object",
            name: "rozcestnikCards",
            label: "Rozcestník — Karty",
            list: true,
            fields: [
              { type: "string", name: "title", label: "Název" },
              { type: "string", name: "description", label: "Popis", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "partners",
            label: "Partneři",
            list: true,
            fields: [
              { type: "string", name: "name", label: "Název", required: true },
              { type: "image", name: "logo", label: "Logo" },
              { type: "string", name: "website", label: "Web URL" },
            ],
          },
        ],
        ui: {
          router: () => "/",
          allowedActions: { create: false, delete: false },
        },
      },
      {
        name: "jakpomoci",
        label: "Jak pomoci",
        path: "content/pages",
        match: { include: "jak-pomoci" },
        fields: [
          { type: "string", name: "heroTitle", label: "Hero — Nadpis" },
          { type: "string", name: "heroSubtitle", label: "Hero — Podnadpis" },
          { type: "string", name: "donorInfoHeading", label: "Dárci — Nadpis sekce" },
          { type: "string", name: "donorInfoBody", label: "Dárci — Text", ui: { component: "textarea" } },
          { type: "string", name: "financeHeading", label: "Finance — Nadpis sekce" },
          { type: "string", name: "financeSubheading", label: "Finance — Podnadpis" },
          { type: "string", name: "financeBody1", label: "Finance — Odstavec 1", ui: { component: "textarea" } },
          { type: "string", name: "financeBody2", label: "Finance — Odstavec 2", ui: { component: "textarea" } },
          { type: "string", name: "donationHeading", label: "Darování — Nadpis" },
          { type: "string", name: "donationIntro", label: "Darování — Úvod", ui: { component: "textarea" } },
          {
            type: "object",
            name: "donationTiers",
            label: "Darování — Úrovně",
            list: true,
            fields: [
              { type: "string", name: "amount", label: "Částka" },
              { type: "string", name: "desc", label: "Popis" },
              { type: "boolean", name: "featured", label: "Zvýraznit" },
            ],
          },
          { type: "string", name: "transparencyHeading", label: "Transparentnost — Nadpis" },
          { type: "string", name: "transparencyIntro", label: "Transparentnost — Úvod", ui: { component: "textarea" } },
          { type: "string", name: "bankTransferHeading", label: "Bankovní převod — Nadpis" },
          { type: "string", name: "accountNumber", label: "Číslo účtu" },
          { type: "string", name: "iban", label: "IBAN" },
          { type: "string", name: "swift", label: "SWIFT" },
          { type: "string", name: "variableSymbol", label: "Variabilní symbol" },
          { type: "string", name: "transferMessage", label: "Zpráva pro příjemce" },
          { type: "image", name: "qrCodeImage", label: "QR kód (obrázek)" },
          { type: "string", name: "transactionLinkLabel", label: "Výpis transakcí — text odkazu" },
          { type: "string", name: "transactionLinkHref", label: "Výpis transakcí — URL" },
          { type: "string", name: "donationContractLabel", label: "Darovací smlouva — text tlačítka" },
          { type: "string", name: "sponsoringHeading", label: "Sponzoring — Nadpis" },
          { type: "string", name: "sponsoringIntro", label: "Sponzoring — Úvod", ui: { component: "textarea" } },
          { type: "string", name: "sponsoringBenefits", label: "Sponzoring — výhody", list: true },
          { type: "string", name: "volunteeringHeading", label: "Dobrovolnictví — Nadpis" },
          { type: "string", name: "volunteeringIntro", label: "Dobrovolnictví — Úvod", ui: { component: "textarea" } },
          { type: "string", name: "volunteeringRequirements", label: "Dobrovolnictví — požadavky", list: true },
        ],
        ui: {
          router: () => "/jak-pomoci",
          allowedActions: { create: false, delete: false },
        },
      },
      {
        name: "kontakt",
        label: "Kontakt",
        path: "content/pages",
        match: { include: "kontakt" },
        fields: [
          { type: "string", name: "heroTitle", label: "Hero — Nadpis" },
          { type: "string", name: "heroSubtitle", label: "Hero — Podnadpis" },
          { type: "string", name: "contactHeading", label: "Kontakt — Nadpis sekce" },
          { type: "image", name: "organizerPhoto", label: "Organizátorka — Fotka" },
          { type: "string", name: "organizerName", label: "Organizátorka — Jméno" },
          { type: "string", name: "organizerRole", label: "Organizátorka — Role/pozice" },
          { type: "string", name: "phone", label: "Telefon" },
          { type: "string", name: "email", label: "Email" },
          { type: "string", name: "facebookLabel", label: "Facebook — text odkazu" },
          { type: "string", name: "facebookHref", label: "Facebook — URL" },
          { type: "string", name: "instagramLabel", label: "Instagram — text odkazu" },
          { type: "string", name: "instagramHref", label: "Instagram — URL" },
          { type: "string", name: "affiliationLabel", label: "Záštita — název" },
          { type: "string", name: "affiliationHref", label: "Záštita — URL" },
        ],
        ui: {
          router: () => "/kontakt",
          allowedActions: { create: false, delete: false },
        },
      },
      {
        name: "global",
        label: "Globální — Footer & Statistiky",
        path: "content/pages",
        match: { include: "global" },
        fields: [
          {
            type: "object",
            name: "stats",
            label: "Statistiky",
            list: true,
            fields: [
              { type: "string", name: "value", label: "Hodnota" },
              { type: "string", name: "label", label: "Popis" },
            ],
          },
          { type: "string", name: "footerTagline", label: "Footer — Popis kempu", ui: { component: "textarea" } },
          { type: "string", name: "footerContactName", label: "Footer — Kontakt jméno" },
          { type: "string", name: "footerEmail", label: "Footer — Email" },
          { type: "string", name: "footerFacebookLabel", label: "Footer — Facebook text" },
          { type: "string", name: "footerFacebookHref", label: "Footer — Facebook URL" },
          { type: "string", name: "footerInstagramLabel", label: "Footer — Instagram text" },
          { type: "string", name: "footerInstagramHref", label: "Footer — Instagram URL" },
        ],
        ui: {
          allowedActions: { create: false, delete: false },
        },
      },
    ],
  },
});
